#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Automobile.Mobile.Android.Resource", IsApplication=true)]

namespace Automobile.Mobile.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int phone_icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int ConnectionGroup = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int ConnectionStringTextView = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int MainView = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int ServerLayout = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int StartAutomation = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int dbButton = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int directButton = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int registrarButton = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int textView1 = 2131034114;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ConnectionString = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int ConnectionType = 2130968576;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
